### PR TITLE
[ENH] Update meta classes and add unit tests

### LINKED ISSUE #106: [ENH] Refactor `skbase.base._meta` and add unit tests
**Is your feature request related to a problem? Please describe.**
The meta-base-class functionality needs to be updated to align with [SBEP1](https://github.com/sktime/skbase/blob/main/enhancement_proposals/sbep_1.md). We also need to add unit tests covering all the meta-base-class functionality.

Completing this should also fix #81.

### PR DESCRIPTION
**Pull request by RNKuhns**
#### Reference Issues/PRs
Fixes #106.

#### What does this implement/fix? Explain your changes.
This PR will add unit tests of the meta class functionality. It will also provide an update of the provided functionality to make it generally consistent with `skbase` design principles.

#### Does your contribution introduce a new dependency? If yes, which one?
No new dependencies.

#### What should a reviewer concentrate their feedback on?
Updates to BaseMetaObject (renamed from BaseMetaEstimator) and whether tests cover reasonable use-cases.

### CODE REVIEW

**Review by fkiraly — APPROVED** [review]
Ah yes, I forgot to port this. Good spot.

**Comment by fkiraly** [comment]
maybe one thing for you to review, whether you like (or not) the implied inheritance order.

**Comment by RNKuhns** [comment]
> maybe one thing for you to review, whether you like (or not) the implied inheritance order.

Do you mean in downsteram usage? 

```python

class SomePipeline(BaseMetaObject, BaseObject):
    ...
```

**Comment by RNKuhns** [comment]
@fkiraly I'm going to leave this open for a bit and add unit tests of this functionality. For ease, can you point me to related `sktime` unit tests. I didn't see any directly testing this where the `sktime.base` tests were located, but there is test coverage. Is this handled in tests of classes using `_HeterogeneousMetaEstimator`?

**Comment by fkiraly** [comment]
> Do you mean in downsteram usage?

Yes

> @fkiraly I'm going to leave this open for a bit and add unit tests of this functionality. For ease, can you point me to related sktime unit tests. I didn't see any directly testing this where the sktime.base tests were located, but there is test coverage. Is this handled in tests of classes using _HeterogeneousMetaEstimator?

Yes, correct - most of the coverage comes from integration tests which *require* the functionality in the mixin to work correctly in order to pass.

I also do not think there are *any* direct tests, but I might be mistaken.

**Comment by RNKuhns** [comment]
> > Do you mean in downsteram usage?
> 
> Yes.
> 
> One issue that for me has recently come up is that the meta-estimator can be a `BaseObject` and not `BaseEstimator`, or it can be both.
> 
> In either case, it makes sense to implement default functionality for the parameter getters `get_params`, `get_fitted_params`, but the second one is only "present" for `BaseEstimator` descendants.

I'm thinking we might want want 2 mixins.

1. `BaseMetaObject mixin that has meta `get_params` and `set_params` (and other functionaly that applies to objects and estimators).
2. `BaseMetaEstimator` mixin that inherits from `BaseMetaObject` (does alll the same stuff), and also has estimator specific things like retrieving fitted parameters. 

From a user perspective,  we'd document that the choice of the mixin to use is dependent on whether your building a meta object or meta estimator, which seems straight-forward enough. For example:

```python
from skbase.base import BaseEstimator, BaseMetaestimator, BaseMetaObject, BaseObject

class SomeNeatMetaObject(BaseMetaObject, BaseObject):
    ...

class SomeNeatMetaEstimator(BaseMetaEstimator, BaseEstimator):
    ...
```

From a maintenance perspective, we'd have the same functionality and not double anything up.

I'll work up this and some integration tests today.

**Comment by fkiraly** [comment]
> From a maintenance perspective, we'd have the same functionality and not double anything up.

I suppose that makes sense, assuming they are clearly presented as mixins.

**Pull request merged**
