### PR TITLE
Post Release Documentation Fixes

### LINKED ISSUE #54: [DOC] Add sphinx-copybutton extension
#### Describe the issue linked to the documentation

The [sphinx-copybutton](https://sphinx-copybutton.readthedocs.io/en/latest/index.html) package provides a nice sphinx extension to make it easy to copy code blocks.

#### Suggest a potential alternative/fix

We should add this. It will make it easier to copy the code blocks in the install instructions now, and all the code examples later.

### PR DESCRIPTION
**Pull request by RNKuhns**
#### What does this implement/fix? Explain your changes.
This PR includes some documentation improvements that became apparent after the initial package release. This includes fixes to update the project's sphinx config file, so it correctly lists the project as `skbase`.

Other minor changes include:

- Minor tweaks to the `pydata-sphinx-theme` configuration including, adding a light/dark theme toggle and icon link (at end of top navbar) to pypi.
- Dynamically setting the copyright year
- Getting version by importing `skbase` instead of hardcoding it in `conf.py`
- Adding sphinx-copybutton extension that fixes #54 
- Fixes 3 typos (user guide heading and 2 references on get started page) that had dash instead of apostrophe when trying to reference multiple `BaseObjects` but typed `BaseObject-s`

#### Does your contribution introduce a new dependency? If yes, which one?
No.

#### What should a reviewer concentrate their feedback on?

Does the documentation configuration look correct? Other than the 3 typos, no changes to documentation content are included. Any doc content changes will be handled in separate PRs.

#### Any other comments?
None.

### CODE REVIEW

**Comment by RNKuhns** [comment]
@fkiraly can you take a quick look at this PR. Only tricky part was figuring out how to let us import skbase in the conf.py without having a CI error.

Just importing skbase locally (assuming editable install) would let you run pytest without errors. But in CI it would lead to collection errors (because it was finding the tests but not from expected "locations"). Excluding the docs folder from pytest solves the problem.

**Comment by fkiraly** [comment]
> Just importing skbase locally (assuming editable install) would let you run pytest without errors. But in CI it would lead to collection errors (because it was finding the tests but not from expected "locations"). Excluding the docs folder from pytest solves the problem.

Do you have an explanation for that?

**Comment by RNKuhns** [comment]
> Looks simple enough, great!
> 
> * I would leave "API reference" as such, since API feels more vague/unspeific.
> * is there not a way to automatically update the switcher?
> * regarding `BaseObjects`, I think the in-line code formatting should apply only to object names. I.e., it would be `BaseObject`-s and not `BaseObjects`, because the object is called `BaseObject` and there isn't a class called `BaseObjects`

- I'm fine reverting to "API Reference". 
- Unfortunately, there isn't a built-in way to automatically update the switcher. Though the update is formulaic (increment the name of the switcher item pointing to the stable release to the newest release version, and add an item that points to the prior version's docs (which was previously accessible through stable). We might be able to automate that later on, but will need to remember to increment things as part of our release process in the short-run.
- I'm fine using ``BaseObject``-s (even if I don't like it visually).

**Comment by RNKuhns** [comment]
> > Just importing skbase locally (assuming editable install) would let you run pytest without errors. But in CI it would lead to collection errors (because it was finding the tests but not from expected "locations"). Excluding the docs folder from pytest solves the problem.
> 
> Do you have an explanation for that?

I wish I had a good explanation for why this happens. But I tested and confirmed it is the import of skbase to dynamically determine the version that caused the issue. After going around in a circle for a while, I compared the config with sktime and noticed the difference I've changed here, and it fixed it.

**Comment by RNKuhns** [comment]
@fkiraly I think I've addressed your comments, let me know if this is okay to merge.

**Review by fkiraly — APPROVED** [review]
Happy with this in-principle!

As said, the switcher update makes the process more brittle (easy to forget that step), but I do not have a strong opinion.

**Comment by RNKuhns** [comment]
@fkiraly I like the idea of the switcher (being able to see docs for different versions). I'm willing to make step-by-step instructions for the release procedures so we don't forget to make that update.

**Pull request merged**
