### PR TITLE
[ENH] Add vs code settings and auto generated api area to .gitignore

### PR DESCRIPTION
**Pull request by RNKuhns**
#### Reference Issues/PRs

None

#### What does this implement/fix? Explain your changes.

Makes minor updates to the .gitignore file (I believe @achieveordie may have suggested these somewhere).

#### Does your contribution introduce a new dependency? If yes, which one?

None

##### For all contributions
- [x] I've reviewed the project documentation on [contributing](https://skbase.readthedocs.io/en/latest/contribute.html)
- [x] I've added myself to the [list of contributors](https://github.com/sktime/skbase/blob/main/.all-contributorsrc).
- [x] The PR title starts with either [ENH], [CI/CD], [MNT], [DOC], or [BUG] indicating whether
  the PR topic is related to enhancement, CI/CD, maintenance, documentation, or a bug.

##### For code contributions
- [ ] Unit tests have been added covering code functionality
- [ ] Appropriate docstrings have been added (see [documentation standards](https://skbase.readthedocs.io/en/latest/contribute/development/developer_guide/creating_docs.html))
- [ ] New public functionality has been added to the API Reference

### CODE REVIEW

**Review by fkiraly — APPROVED** [review]
Makes sense.

Can you quickly point me to the artefact that auto-generates `docs/source/api_reference`?

**Comment by RNKuhns** [comment]
> Makes sense.
> 
> 
> 
> Can you quickly point me to the artefact that auto-generates `docs/source/api_reference`?

I'm pretty sure that is in api_reference.rst. In the "autosummary" directives it specified "toctree" which is where the auto-generated docs get sent.

**Comment by fkiraly** [comment]
oh, that. Why would we need to add this to `gitignore`?
The same mechanism exists in `sktime` and it never generates local files for me in the `docs/source` dir and subdirs.

**Comment by RNKuhns** [comment]
It does generate them if you build the docs locally.

And we don't need/want them in GH repo in that case.

**Comment by fkiraly** [comment]
ah. Makes sense. Well, I've approved it anyway, assuming that it makes sense.

**Pull request merged**
